import React, { useState } from 'react';
import {
  Smartphone,
  ExternalLink,
  QrCode,
  Copy,
  Check,
  Play,
  Sparkles,
  Zap,
  Download,
} from 'lucide-react';
import { backgroundRunner } from '../lib/backgroundService';

interface AndroidToolsViewProps {
  onSelectConfig: (url: string) => void;
  onRunConfig: () => void;
  onOpenAPKModal: () => void;
}

const SAMPLE_CONFIGS = [
  {
    name: 'Cloudflare Worker CDN VLESS',
    protocol: 'VLESS',
    url: 'vless://d342d11e-d424-4583-b36e-524ab1f0afa4@speed.cloudflare.com:443?encryption=none&security=tls&sni=speed.cloudflare.com&fp=chrome&type=ws&path=%2F#Cloudflare%20Speedtest%20CDN',
    desc: 'Optimized for Fragment & Fingerprint enhancement test',
  },
  {
    name: 'Google DNS Cloud Gateway Trojan',
    protocol: 'Trojan',
    url: 'trojan://password123@dns.google:443?security=tls&sni=dns.google&fp=chrome&type=ws&path=%2Fdns-query#Google%20DoH%20Gateway',
    desc: 'Clean TLS endpoint ideal for testing chain proxy & fragment mask',
  },
  {
    name: 'AdGuard TLS Node VLESS',
    protocol: 'VLESS',
    url: 'vless://00000000-0000-0000-0000-000000000000@dns.adguard-dns.com:443?encryption=none&security=tls&sni=dns.adguard-dns.com&fp=chrome&type=tcp#AdGuard%20TLS',
    desc: 'High-speed encrypted endpoint with TLS support',
  },
];

export const AndroidToolsView: React.FC<AndroidToolsViewProps> = ({
  onSelectConfig,
  onRunConfig,
  onOpenAPKModal,
}) => {
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  const handleCopy = async (text: string, idx: number) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedIdx(idx);
      setTimeout(() => setCopiedIdx(null), 2000);
    } catch {}
  };

  const handleRunSample = (cfg: (typeof SAMPLE_CONFIGS)[0]) => {
    backgroundRunner.startService({
      name: cfg.name,
      server: cfg.url.split('@')[1].split(':')[0],
      port: 443,
      protocol: cfg.protocol.toLowerCase(),
    });
    onRunConfig();
  };

  return (
    <div className="space-y-6">
      {/* APK Download Banner */}
      <div className="bg-gradient-to-r from-[#4cdf86]/15 via-[#3cd4f0]/10 to-[#7c5cff]/15 border border-[#4cdf86]/35 rounded-2xl p-5 backdrop-blur-xl shadow-xl">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-[#4cdf86]/20 flex items-center justify-center border border-[#4cdf86]/40 text-[#4cdf86]">
              <Smartphone className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">فایل نصبی اندروید (APK) و وب‌اپ</h3>
              <p className="text-xs text-gray-300">
                دریافت مستقیم فایل .apk یا نصب آنی WebAPK با یک تپ روی گوشی
              </p>
            </div>
          </div>

          <button
            onClick={onOpenAPKModal}
            className="flex items-center gap-2 py-2.5 px-5 bg-gradient-to-r from-[#4cdf86] to-[#3cd4f0] text-black font-bold text-xs rounded-xl shadow-lg shadow-[#4cdf86]/20 hover:opacity-95 transition active:scale-95"
          >
            <Download className="w-4 h-4" />
            <span>دانلود و نصب APK</span>
          </button>
        </div>
      </div>

      {/* Client Quick Launchers */}
      <div className="bg-[#161623]/90 border border-white/10 rounded-2xl p-5 backdrop-blur-xl shadow-xl">
        <div className="flex items-center gap-2 mb-3">
          <Smartphone className="w-5 h-5 text-[#3cd4f0]" />
          <h3 className="text-sm font-semibold text-white">Recommended Android Clients</h3>
        </div>
        <p className="text-xs text-gray-400 mb-4 leading-relaxed">
          The configurations generated by Proxy Builder are fully compatible with modern Android proxy clients:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <a
            href="https://github.com/MatsuriDayo/NekoBoxForAndroid/releases"
            target="_blank"
            rel="noreferrer"
            className="flex items-center justify-between p-3.5 bg-[#0f0f19] hover:bg-[#1a1a2e] border border-white/10 rounded-xl transition group"
          >
            <div>
              <h4 className="text-xs font-semibold text-white group-hover:text-[#3cd4f0] transition">
                NekoBox for Android
              </h4>
              <p className="text-[11px] text-gray-400">Best for Sing-box chained JSON & Tun mode</p>
            </div>
            <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-white" />
          </a>

          <a
            href="https://github.com/2dust/v2rayNG/releases"
            target="_blank"
            rel="noreferrer"
            className="flex items-center justify-between p-3.5 bg-[#0f0f19] hover:bg-[#1a1a2e] border border-white/10 rounded-xl transition group"
          >
            <div>
              <h4 className="text-xs font-semibold text-white group-hover:text-[#7c5cff] transition">
                v2rayNG
              </h4>
              <p className="text-[11px] text-gray-400">Best for Xray JSON, VLESS, VMess & Trojan URLs</p>
            </div>
            <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-white" />
          </a>

          <a
            href="https://github.com/patterniha/PattNG/releases"
            target="_blank"
            rel="noreferrer"
            className="flex items-center justify-between p-3.5 bg-[#0f0f19] hover:bg-[#1a1a2e] border border-white/10 rounded-xl transition group"
          >
            <div>
              <h4 className="text-xs font-semibold text-white group-hover:text-[#5c8cff] transition">
                PattNG (Android)
              </h4>
              <p className="text-[11px] text-gray-400">Native support for cs, fm and fp parameters</p>
            </div>
            <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-white" />
          </a>

          <a
            href="https://github.com/SagerNet/sing-box/releases"
            target="_blank"
            rel="noreferrer"
            className="flex items-center justify-between p-3.5 bg-[#0f0f19] hover:bg-[#1a1a2e] border border-white/10 rounded-xl transition group"
          >
            <div>
              <h4 className="text-xs font-semibold text-white group-hover:text-[#4cdf86] transition">
                SagerNet / Sing-box
              </h4>
              <p className="text-[11px] text-gray-400">Official Android core client for Sing-box</p>
            </div>
            <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-white" />
          </a>
        </div>
      </div>

      {/* Preset Test Configurations */}
      <div className="bg-[#161623]/90 border border-white/10 rounded-2xl p-5 backdrop-blur-xl shadow-xl">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-[#7c5cff]" />
            <h3 className="text-sm font-semibold text-white">Sample Test Configurations</h3>
          </div>
          <span className="text-[11px] text-gray-500">Ready to load</span>
        </div>
        <p className="text-xs text-gray-400 mb-4 leading-relaxed">
          Use these test configurations to test Fragment Enhancement, Chaining, and Background Runner without manual setup:
        </p>

        <div className="space-y-3">
          {SAMPLE_CONFIGS.map((cfg, idx) => (
            <div
              key={idx}
              className="p-3.5 bg-[#0f0f19] border border-white/10 rounded-xl space-y-2 hover:border-white/20 transition"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-[#7c5cff]/20 text-[#7c5cff] border border-[#7c5cff]/30">
                    {cfg.protocol}
                  </span>
                  <h4 className="text-xs font-bold text-white">{cfg.name}</h4>
                </div>

                <div className="flex items-center gap-1.5">
                  <button
                    onClick={() => handleCopy(cfg.url, idx)}
                    className="p-1.5 text-xs text-gray-400 hover:text-white bg-white/5 rounded-lg border border-white/10 transition"
                    title="Copy URL"
                  >
                    {copiedIdx === idx ? <Check className="w-3.5 h-3.5 text-[#4cdf86]" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>

                  <button
                    onClick={() => onSelectConfig(cfg.url)}
                    className="px-2.5 py-1 text-xs font-semibold text-[#7c5cff] bg-[#7c5cff]/15 hover:bg-[#7c5cff]/25 rounded-lg border border-[#7c5cff]/30 transition"
                  >
                    Enhance
                  </button>

                  <button
                    onClick={() => handleRunSample(cfg)}
                    className="px-2.5 py-1 text-xs font-semibold text-[#4cdf86] bg-[#4cdf86]/15 hover:bg-[#4cdf86]/25 rounded-lg border border-[#4cdf86]/30 transition flex items-center gap-1"
                  >
                    <Play className="w-3 h-3 fill-current" />
                    <span>Run</span>
                  </button>
                </div>
              </div>

              <p className="text-[11px] text-gray-400">{cfg.desc}</p>
              <p className="text-[10px] text-gray-500 font-mono truncate">{cfg.url}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
